sudo: required
services:
- docker
install:
- sudo apt-get update -qq
- sudo apt-get install -qq qt5-default qttools5-dev-tools qtdeclarative5-dev libqt5webkit5-dev libqt5gui5
- qmake -version
script:
- qmake -project
- qmake mdxfind-gui.pro
- make
notifications:
  email:
    on_success: never
    on_failure: always
